[tool.ruff]
line-length = 100
target-version = "py312"
fix = true
select = ["E","F","I","UP","B","SIM"]
ignore = []

[tool.mypy]
python_version = "3.12"
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
strict = true
plugins = []
